# Generated by Django 4.2.4 on 2023-08-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='price_per_night',
            new_name='room_charge',
        ),
    ]
