# Generated by Django 4.2.4 on 2023-08-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_rename_price_per_night_room_room_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room'),
        ),
    ]
