# Generated by Django 4.2.4 on 2023-08-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_remove_room_image_roomtype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
