# Generated by Django 4.2.4 on 2023-08-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_room_check_in_date_room_check_out_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='check_out_date',
        ),
    ]
