# Generated by Django 4.2.4 on 2023-08-12 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=64)),
                ('gender', models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='razor_pay_order_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='razor_pay_payment_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='razor_pay_payment_signature',
        ),
        migrations.AddField(
            model_name='ticket',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.EmailField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='ticket',
            name='mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_class',
            field=models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first', 'First')], default='economy', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='Pending', max_length=45),
        ),
        migrations.AddField(
            model_name='ticket',
            name='passengers',
            field=models.ManyToManyField(related_name='flight_tickets', to='accounts.passenger'),
        ),
    ]
