# Generated by Django 4.2.4 on 2023-08-13 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_ticket_razor_pay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='coupon_discount',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='coupon_used',
        ),
    ]
